[package]
authors = ["Joseph Gentle <me@josephg.com>"]
name = "text"
version = "0.1.0"
edition = "2018"

[dependencies]
smartstring = "0.2.9"
smallvec = { version = "1.6.1", features = ["union"] }

[dev-dependencies]
json = "0.11.13"